version: '2'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    networks:
      - spring

networks:
  spring:
    driver: bridge